# Generated by Django 3.2.6 on 2022-03-01 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseuser', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verify_date',
            field=models.DateTimeField(default='1900-01-01 00:00:00', verbose_name='邮箱验证日期'),
        ),
    ]
