# Generated by Django 3.2.6 on 2022-04-07 02:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseuser', '0004_user_verify_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verify_date',
            field=models.DateTimeField(default=datetime.datetime(1900, 1, 1, 0, 0), verbose_name='邮箱验证日期'),
        ),
    ]
