# Generated by Django 3.2.6 on 2022-05-06 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserctrlApp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('app_name', models.CharField(max_length=100)),
                ('app_id', models.CharField(max_length=255, unique=True)),
                ('app_secret', models.CharField(max_length=255)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'userctrl_app',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserctrlOperation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('oper_name', models.CharField(max_length=100)),
                ('oper_code', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'userctrl_operation',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserctrlResourcetype',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('resrc_name', models.CharField(blank=True, max_length=100, null=True)),
                ('resrc_table', models.CharField(default='', max_length=100)),
            ],
            options={
                'db_table': 'userctrl_resourcetype',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserctrlResrc',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('resrc_name', models.CharField(max_length=100)),
                ('resrc_code', models.CharField(max_length=100)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userctrl.userctrlapp')),
                ('resrc_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='userctrl.userctrlresourcetype')),
            ],
            options={
                'db_table': 'userctrl_resrc',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserctrlResrcOperation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ctrl_name', models.CharField(max_length=100)),
                ('ctrl_code', models.CharField(max_length=100)),
                ('remark', models.CharField(blank=True, max_length=100, null=True)),
                ('oper', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='userctrl.userctrloperation')),
                ('resr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userctrl.userctrlresrc')),
            ],
            options={
                'db_table': 'userctrl_resrc_operation',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserctrlRole',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=100)),
                ('role_code', models.CharField(max_length=100, unique=True)),
                ('parent_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'userctrl_role',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserctrlUsergroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=100)),
                ('group_code', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'userctrl_usergroup',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserctrlUsergroupCtrl',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('has_expect', models.BooleanField()),
                ('expect_time', models.DateTimeField(blank=True, null=True)),
                ('is_on', models.BooleanField(default=True)),
                ('ctrl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userctrl.userctrlresrcoperation')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userctrl.userctrlusergroup')),
            ],
            options={
                'db_table': 'userctrl_usergroup_ctrl',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserctrlUsergroupBaseuser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userctrl.userctrlusergroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'userctrl_usergroup_baseuser',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserctrlRoleCtrl',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('has_expect', models.BooleanField()),
                ('expect_time', models.DateTimeField(blank=True, null=True)),
                ('is_on', models.BooleanField(default=True)),
                ('ctrl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userctrl.userctrlresrcoperation')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userctrl.userctrlrole')),
            ],
            options={
                'db_table': 'userctrl_role_ctrl',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserctrlRoleBaseuser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userctrl.userctrlrole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'userctrl_role_baseuser',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserctrlResrcmenu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('menu_name', models.CharField(max_length=100)),
                ('target_url', models.CharField(max_length=255)),
                ('parent_id', models.IntegerField(blank=True, null=True)),
                ('end_type', models.CharField(blank=True, max_length=20, null=True)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('resrc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userctrl.userctrlresrc')),
            ],
            options={
                'db_table': 'userctrl_resrcmenu',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserctrlResrcfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=255)),
                ('end_type', models.CharField(blank=True, max_length=20, null=True)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('resrc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userctrl.userctrlresrc')),
            ],
            options={
                'db_table': 'userctrl_resrcfile',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserctrlResrcelement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ele_name', models.CharField(max_length=100)),
                ('ele_id', models.CharField(blank=True, max_length=128, null=True)),
                ('ele_class', models.CharField(blank=True, max_length=128, null=True)),
                ('ele_tag', models.CharField(max_length=50)),
                ('end_type', models.CharField(blank=True, max_length=20, null=True)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('resrc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userctrl.userctrlresrc')),
            ],
            options={
                'db_table': 'userctrl_resrcelement',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserctrlResrcdata',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_name', models.CharField(max_length=100)),
                ('api_url', models.CharField(max_length=255)),
                ('end_type', models.CharField(blank=True, max_length=20, null=True)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('resrc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userctrl.userctrlresrc')),
            ],
            options={
                'db_table': 'userctrl_resrcdata',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserctrlBaseuserCtrl',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('has_expect', models.BooleanField()),
                ('expect_time', models.DateTimeField(blank=True, null=True)),
                ('is_on', models.BooleanField(default=True)),
                ('ctrl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userctrl.userctrlresrcoperation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'userctrl_baseuser_ctrl',
                'managed': True,
            },
        ),
    ]
