# Generated by Django 3.2.6 on 2022-05-06 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userctrl', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userctrlresrc',
            old_name='resrc_name',
            new_name='type_name',
        ),
    ]
