# Generated by Django 3.2.6 on 2022-05-06 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userctrl', '0003_auto_20220506_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userctrlresrc',
            name='resrc_code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
