# Generated by Django 3.2.6 on 2022-05-07 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userctrl', '0004_alter_userctrlresrc_resrc_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userctrlresrcoperation',
            old_name='resr',
            new_name='resrc',
        ),
    ]
