# Generated by Django 3.2.6 on 2022-05-08 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userctrl', '0005_rename_resr_userctrlresrcoperation_resrc'),
    ]

    operations = [
        migrations.AddField(
            model_name='userctrlusergroup',
            name='remark',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
