# Generated by Django 3.2.6 on 2022-05-08 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userctrl', '0006_userctrlusergroup_remark'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userctrlrolectrl',
            constraint=models.UniqueConstraint(fields=('role', 'ctrl'), name='unique_ctrl_role'),
        ),
    ]
