# Generated by Django 3.2.6 on 2022-05-08 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userctrl', '0008_auto_20220508_1712'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userctrlusergroupctrl',
            name='unique_ctrl_group',
        ),
    ]
