# Generated by Django 3.2.6 on 2022-05-08 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userctrl', '0009_remove_userctrlusergroupctrl_unique_ctrl_group'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userctrlusergroupctrl',
            constraint=models.UniqueConstraint(fields=('ctrl', 'group'), name='unique_ctrl_group'),
        ),
    ]
